import React, { useEffect, useRef, useState, useMemo } from "react";
import { type InventoryForm } from "../../interfaces";

// تعريف شكل البيانات لكل نتيجة بحث
interface FuzzyMatchItem {
  matched_id: number;
  name_en: string;
  name_ar: string;
  // ✅ ADDED: full_path support
  full_path?: string;
  score: number;
  type: "exact" | "fuzzy";
}

interface AIPanelProps {
  whatsappInput?: string;
  setWhatsappInput: (input: string) => void;
  aiResponseRaw: string;
  loading: boolean;
  message: string;
  userName?: string;
  userPhone?: string;
  phoneStatus: "Inventory" | "Request";
  setPhoneStatus: (status: "Inventory" | "Request") => void;
  customerName?: string;
  customerId?: string;
  form: InventoryForm;
  onGenerate: () => void;
  onConfirm: () => void;
  setAiResponseRaw: (aiResponse: string) => void;

  // --- New Props for Fuzzy Location Logic ---
  fuzzyLocationInput: string;
  setFuzzyLocationInput: (input: string) => void;
  fuzzyLocationResponse: string;
  setFuzzyLocationResponse: (response: string) => void;
  onFuzzySearch: () => void;
  onConfirmFuzzyLocation: (
    selectedLocations: { id: number; name: string }[]
  ) => void;
  fuzzyLoading?: boolean;
}

export const AIPanel: React.FC<AIPanelProps> = ({
  whatsappInput,
  setWhatsappInput,
  aiResponseRaw,
  loading,
  message,
  phoneStatus,
  setPhoneStatus,
  customerName,
  customerId,
  userName,
  userPhone,
  form,
  onGenerate,
  onConfirm,
  setAiResponseRaw,
  // --- Destructure New Props ---
  fuzzyLocationInput,
  setFuzzyLocationInput,
  fuzzyLocationResponse,
  setFuzzyLocationResponse,
  onFuzzySearch,
  onConfirmFuzzyLocation,
  fuzzyLoading = false,
}) => {
  // Track if first generation has been triggered
  const hasAutoGeneratedRef = useRef(false);

  // State لتخزين الـ IDs اللي اليوزر اختارها من القائمة
  const [selectedMatchIds, setSelectedMatchIds] = useState<number[]>([]);

  // ----------------------------------------------------------------
  // 1. Auto-generate Logic
  // ----------------------------------------------------------------
  useEffect(() => {
    if (!hasAutoGeneratedRef.current && whatsappInput && whatsappInput.trim()) {
      hasAutoGeneratedRef.current = true;
      setTimeout(() => {
        onGenerate();
      }, 100);
    }
  }, [whatsappInput, onGenerate]);

  // Keep local editable response in sync when new AI output comes in
  useEffect(() => {
    setAiResponseRaw(aiResponseRaw);
    if (aiResponseRaw) {
      onConfirm(); // Update main form temporarily (excluding location logic handled in hook)
    }
  }, [aiResponseRaw, setAiResponseRaw]);

  // ----------------------------------------------------------------
  // 2. Extract 'location' from AI JSON to Fuzzy Input (FIXED)
  // ----------------------------------------------------------------
  useEffect(() => {
    if (aiResponseRaw) {
      try {
        const parsed = JSON.parse(aiResponseRaw);
        // Handle both Array structure (new API) and Object structure
        const data = Array.isArray(parsed.data) ? parsed.data[0] : parsed.data;

        let extractedLocation = "";

        // Check for 'location' string or 'locations' array
        if (
          data?.locations_text &&
          typeof data.locations_text === "string" &&
          data.locations_text !== "Not provided"
        ) {
          extractedLocation = data.locations_text;
        } else if (
          data?.locations &&
          Array.isArray(data.locations) &&
          data.locations.length > 0
        ) {
          // ✅ FIX: Join all locations with comma instead of taking just the first one
          // This ensures all request locations are sent to the fuzzy search
          extractedLocation = data.locations
            .filter((l: unknown) => typeof l === "string")
            .join(", ");
        } else if (
          data?.location &&
          typeof data.location === "string" &&
          data.location !== "Not provided"
        ) {
          extractedLocation = data.location;
        }

        // Only update if we found a valid location
        if (extractedLocation) {
          setFuzzyLocationInput(extractedLocation);
        }
      } catch {
        // Ignore JSON parse errors while typing
      }
    }
  }, [aiResponseRaw, setFuzzyLocationInput]);

  // ----------------------------------------------------------------
  // 3. Parse Fuzzy Response & Pre-select Logic
  // ----------------------------------------------------------------
  const parsedMatches = useMemo(() => {
    if (!fuzzyLocationResponse) return [];
    try {
      const res = JSON.parse(fuzzyLocationResponse);
      const exact = (res.exact_matches || []).map(
        (m: {
          score: number;
          matched_id: number;
          name_en: string;
          name_ar: string;
          full_path: string;
        }) => ({
          ...m,
          type: "exact",
        })
      );
      const fuzzy = (res.fuzzy_matches || []).map(
        (m: {
          score: number;
          matched_id: number;
          name_en: string;
          name_ar: string;
          full_path: string;
        }) => ({
          ...m,
          type: "fuzzy",
        })
      );
      return [...exact, ...fuzzy] as FuzzyMatchItem[];
    } catch {
      return [];
    }
  }, [fuzzyLocationResponse]);

  // Logic to auto-select best matches when results arrive
  useEffect(() => {
    if (parsedMatches.length > 0) {
      if (phoneStatus === "Inventory") {
        // Inventory: Auto-select the first (highest score) match
        setSelectedMatchIds([parsedMatches[0].matched_id]);
      } else {
        // Request: Auto-select all Exact Matches
        const exactIds = parsedMatches
          .filter((m) => m.type === "exact")
          .map((m) => m.matched_id);

        if (exactIds.length > 0) {
          setSelectedMatchIds(exactIds);
        } else {
          // If no exact matches, select the first fuzzy match as a fallback
          setSelectedMatchIds([parsedMatches[0].matched_id]);
        }
      }
    } else {
      setSelectedMatchIds([]);
    }
  }, [parsedMatches, phoneStatus]);

  // ----------------------------------------------------------------
  // 4. Handle Selection Logic (Click on List Item)
  // ----------------------------------------------------------------
  const toggleSelection = (id: number) => {
    if (phoneStatus === "Inventory") {
      // Radio behavior: Only one selected at a time
      setSelectedMatchIds([id]);
    } else {
      // Checkbox behavior: Toggle selection
      setSelectedMatchIds((prev) =>
        prev.includes(id) ? prev.filter((x) => x !== id) : [...prev, id]
      );
    }
  };

  // ----------------------------------------------------------------
  // 5. Handle Final Confirm
  // ----------------------------------------------------------------
  const handleFinalConfirm = () => {
    const selectedObjects = parsedMatches
      .filter((m) => selectedMatchIds.includes(m.matched_id))
      .map((m) => ({
        id: m.matched_id,
        // ✅ Use full_path if available, otherwise name_en
        name: m.full_path || m.name_en,
      }));

    onConfirmFuzzyLocation(selectedObjects);
  };

  return (
    <div className="bg-white p-6 rounded-xl shadow-lg h-full flex flex-col overflow-y-auto">
      <h1 className="text-xl font-bold text-gray-900 mb-4">
        Parsing WhatsApp Message
      </h1>

      {/* User Info */}
      <div className="bg-gray-50 p-4 rounded-lg mb-4 grid grid-cols-2 gap-4 text-sm">
        <p>
          WAP Message Type:{" "}
          <span className="font-semibold text-blue-600">{phoneStatus}</span>
        </p>
        <p>
          Telephone Number: <span className="font-semibold">{userPhone}</span>
        </p>
        <p>
          Username: <span className="font-semibold">{userName}</span>
        </p>
        <p>
          Customer ID: <span className="font-semibold">{customerId}</span>
        </p>
        <p className="col-span-2">
          Customer Status:{" "}
          <span className="font-semibold">
            {customerName} ({customerId})
          </span>
        </p>

        <button
          onClick={() =>
            setPhoneStatus(
              phoneStatus === "Inventory" ? "Request" : "Inventory"
            )
          }
          className="col-span-2 bg-yellow-200 text-yellow-800 py-1 rounded-md text-xs font-semibold hover:bg-yellow-300 transition"
        >
          Toggle Message Type: {phoneStatus}
        </button>
      </div>

      {/* WhatsApp Input */}
      <div className="flex-shrink-0 mb-4 border p-4 rounded-lg">
        <div className="flex justify-between items-center mb-2">
          <label className="text-sm font-semibold text-gray-700">
            WAP Message
          </label>
          <div className="text-xs text-gray-500 text-right">
            <span className="block">
              Timestamp: <span className="font-semibold">{form.timestamp}</span>
            </span>
            <span className="block text-gray-700">
              Incoming: <span className="font-semibold">{userPhone}</span>
              <span className="text-xs ml-1 font-normal text-gray-500">
                ({phoneStatus})
              </span>
            </span>
          </div>
        </div>
        <textarea
          rows={4}
          value={whatsappInput}
          onChange={(e) => setWhatsappInput(e.target.value)}
          placeholder="Paste the raw WhatsApp inventory message here..."
          className="w-full p-2 border border-gray-300 rounded-md focus:ring-blue-500 focus:border-blue-500 transition resize-y"
          disabled={loading}
        ></textarea>

        <button
          onClick={onGenerate}
          disabled={loading || !whatsappInput?.trim()}
          className="mt-3 w-full bg-blue-600 text-white py-2 rounded-lg font-semibold shadow-md hover:bg-blue-700 transition disabled:bg-gray-400 disabled:cursor-not-allowed"
        >
          {loading ? "Generating..." : "Generate Data"}
        </button>

        <div className="mt-3 p-2 bg-white rounded-md border border-dashed">
          <p className="font-semibold text-xs text-gray-700 mb-1">
            Image/Media URLs ({form.image_urls.length}):
          </p>
          {form.image_urls.length > 0 ? (
            <ul className="space-y-1 text-blue-600 text-xs">
              {form.image_urls.map((url, index) => (
                <li
                  key={index}
                  className="truncate hover:underline cursor-pointer"
                  title={url}
                >
                  {url}
                </li>
              ))}
            </ul>
          ) : (
            <p className="text-gray-500 italic text-xs">
              No media URLs attached. (AI will try to extract them)
            </p>
          )}
        </div>
      </div>

      {/* AI Response (editable) */}
      <div className="flex flex-col mb-4">
        <div className="flex justify-between items-center mb-2">
          <label className="text-sm font-semibold text-gray-700">
            AI Response: Structured JSON Output
          </label>
          <button
            onClick={() => {
              try {
                const parsed = JSON.parse(aiResponseRaw);
                setAiResponseRaw(JSON.stringify(parsed, null, 2));
              } catch (err) {
                console.error("Invalid JSON format" + err);
              }
            }}
            disabled={!aiResponseRaw.trim()}
            className="text-xs bg-gray-200 text-gray-700 px-3 py-1 rounded hover:bg-gray-300 transition disabled:bg-gray-100 disabled:cursor-not-allowed"
          >
            Format JSON
          </button>
        </div>
        <textarea
          rows={6}
          value={aiResponseRaw}
          onChange={(e) => setAiResponseRaw(e.target.value)}
          className="flex-grow w-full p-3 border border-gray-300 rounded-md bg-white font-mono text-xs overflow-auto focus:ring-blue-500 focus:border-blue-500 transition"
          placeholder="AI generated JSON will appear here..."
        ></textarea>
      </div>

      {/* -------------------------------------------------- */}
      {/* Step 1: Send Fuzzy Location Data                   */}
      {/* -------------------------------------------------- */}
      <div className="flex-shrink-0 mb-4 border p-4 rounded-lg bg-blue-50">
        <label className="text-sm font-semibold text-gray-700 mb-2 block">
          1. Location Search Input (Extracted)
        </label>
        <textarea
          rows={2}
          value={fuzzyLocationInput}
          onChange={(e) => setFuzzyLocationInput(e.target.value)}
          placeholder="Location extracted from AI will appear here..."
          className="w-full p-2 border border-gray-300 rounded-md focus:ring-blue-500 focus:border-blue-500 transition resize-y text-sm"
          disabled={fuzzyLoading}
        ></textarea>

        <button
          onClick={onFuzzySearch}
          disabled={fuzzyLoading || !fuzzyLocationInput?.trim()}
          className="mt-2 w-full bg-cyan-600 text-white py-2 rounded-lg font-semibold shadow-md hover:bg-cyan-700 transition disabled:bg-gray-400 disabled:cursor-not-allowed flex items-center justify-center text-sm"
        >
          {fuzzyLoading ? (
            <span className="flex items-center">
              <svg
                className="animate-spin -ml-1 mr-3 h-5 w-5 text-white"
                xmlns="http://www.w3.org/2000/svg"
                fill="none"
                viewBox="0 0 24 24"
              >
                <circle
                  className="opacity-25"
                  cx="12"
                  cy="12"
                  r="10"
                  stroke="currentColor"
                  strokeWidth="4"
                ></circle>
                <path
                  className="opacity-75"
                  fill="currentColor"
                  d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
                ></path>
              </svg>
              Searching Location...
            </span>
          ) : (
            "Search Location"
          )}
        </button>
      </div>

      {/* -------------------------------------------------- */}
      {/* Step 2: Receive & Select Fuzzy Location Results    */}
      {/* -------------------------------------------------- */}
      <div className="flex-shrink-0 mb-4 border p-4 rounded-lg bg-green-50">
        <div className="flex justify-between items-center mb-2">
          <label className="text-sm font-semibold text-gray-700">
            2. Fuzzy Location Results
          </label>
          <button
            onClick={() => {
              try {
                // Try format if it's JSON
                const parsed = JSON.parse(fuzzyLocationResponse);
                setFuzzyLocationResponse(JSON.stringify(parsed, null, 2));
              } catch {
                // Ignore if not JSON
              }
            }}
            disabled={!fuzzyLocationResponse?.trim()}
            className="text-xs bg-gray-200 text-gray-700 px-3 py-1 rounded hover:bg-gray-300 transition disabled:bg-gray-100 disabled:cursor-not-allowed"
          >
            Format JSON
          </button>
        </div>

        {/* --- JSON TEXTAREA (Restored) --- */}
        <textarea
          rows={4}
          value={fuzzyLocationResponse}
          onChange={(e) => setFuzzyLocationResponse(e.target.value)}
          placeholder="Search results JSON will appear here..."
          className="w-full p-2 border border-gray-300 rounded-md focus:ring-green-500 focus:border-green-500 transition resize-y text-xs font-mono mb-4"
          disabled={fuzzyLoading}
        ></textarea>

        {/* --- SELECTION LIST --- */}
        <label className="text-sm font-semibold text-gray-700 mb-2 block border-t border-gray-300 pt-2">
          Select Correct Location(s)
          {phoneStatus === "Inventory" && (
            <span className="text-xs font-normal ml-1 text-red-600">
              (Select One)
            </span>
          )}
          {phoneStatus === "Request" && (
            <span className="text-xs font-normal ml-1 text-green-600">
              (Select Multiple)
            </span>
          )}
        </label>

        <div className="max-h-60 overflow-y-auto bg-white border border-gray-300 rounded-md mb-3 divide-y">
          {parsedMatches.length === 0 ? (
            <div className="p-4 text-center text-gray-500 text-xs italic">
              {fuzzyLocationResponse
                ? "No matches found in the response."
                : "Waiting for search results..."}
            </div>
          ) : (
            parsedMatches.map((match) => {
              const isSelected = selectedMatchIds.includes(match.matched_id);
              return (
                <div
                  key={match.matched_id}
                  onClick={() => toggleSelection(match.matched_id)}
                  className={`p-2 flex items-center justify-between cursor-pointer hover:bg-gray-50 transition ${
                    isSelected ? "bg-green-50 border-l-4 border-green-500" : ""
                  }`}
                >
                  <div className="flex items-center gap-3">
                    {/* Visual Checkbox/Radio Indicator */}
                    <div
                      className={`w-4 h-4 rounded border flex items-center justify-center transition-colors ${
                        isSelected
                          ? "bg-green-500 border-green-500"
                          : "border-gray-300 bg-white"
                      }`}
                    >
                      {isSelected && (
                        <svg
                          className="w-3 h-3 text-white"
                          fill="none"
                          stroke="currentColor"
                          viewBox="0 0 24 24"
                        >
                          <path
                            strokeLinecap="round"
                            strokeLinejoin="round"
                            strokeWidth="3"
                            d="M5 13l4 4L19 7"
                          ></path>
                        </svg>
                      )}
                    </div>
                    <div>
                      {/* ✅ Display full_path OR name_en */}
                      <p className="text-sm font-medium text-gray-800">
                        {match.full_path || match.name_en}
                      </p>
                      <p className="text-xs text-gray-500">
                        {match.type === "exact" ? (
                          <span className="text-green-600 font-bold">
                            Exact Match
                          </span>
                        ) : (
                          "Fuzzy Match"
                        )}
                      </p>
                    </div>
                  </div>
                  {/* Score Badge */}
                  <div
                    className={`text-xs font-bold px-2 py-1 rounded ${
                      match.score > 90
                        ? "bg-green-100 text-green-800"
                        : match.score > 70
                        ? "bg-yellow-100 text-yellow-800"
                        : "bg-red-100 text-red-800"
                    }`}
                  >
                    {match.score}%
                  </div>
                </div>
              );
            })
          )}
        </div>

        <button
          onClick={handleFinalConfirm}
          disabled={loading || selectedMatchIds.length === 0}
          className="w-full bg-green-600 text-white py-2 rounded-lg font-semibold shadow-md hover:bg-green-700 transition disabled:bg-gray-400 disabled:cursor-not-allowed text-sm"
        >
          Confirm Selection ({selectedMatchIds.length}) & Fill Form
        </button>
      </div>

      {/* Status Message */}
      <div
        className={`mt-4 p-3 rounded-lg text-sm font-medium ${
          message.startsWith("Error")
            ? "bg-red-100 text-red-700"
            : "bg-green-100 text-green-700"
        }`}
      >
        {message || "App ready. Paste message and click Generate Data."}
      </div>
    </div>
  );
};
